services:
  - type: web
    name: findit-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_admin"
    startCommand: "gunicorn lateefah.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.6"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_URL
        sync: false
