# Generated by Django 5.2.14 on 2026-05-26 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_record', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='claims.claim'),
        ),
    ]
