# Generated by Django 5.2.14 on 2026-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admin_query',
            field=models.TextField(blank=True, help_text='Question the admin raises with the claimant while reviewing'),
        ),
    ]
