# Generated by Django 5.2.14 on 2026-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
