# Generated by Django 5.2.14 on 2026-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_model_item_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='owners/'),
        ),
    ]
